#! /usr/bin/env python
# Extract codes from a CSV file

from sys import argv
import csv
import re
from collections import Counter

def extract_codes(infile):
    results = Counter()
    filereader = csv.reader(infile, dialect='unix')
    for row in filereader:
        codes = row[1] or ""
        for code in re.split(r'[,|]', codes):
            code = code.strip().lower()
            results[code] += 1
    return results

def print_codes(counts):
    for code, count in counts.items():
        if code != '':
            print("%d\t%s" % (count, code))
    
if __name__=='__main__':
    result = Counter()
    for arg in argv[1:]:
        with open(arg) as file:
            result.update(extract_codes(file))
    print_codes(result)
